In [4]:
!pip3 install openai=='0.27.0'

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement openai==0.27.0 (from versions: 0.0.2, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.2.1, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5)
ERROR: No matching distribution found for openai==0.27.0


In [2]:
openai.version.VERSION

'0.8.0'

In [1]:
import os
import sys
sys.path.append("../")

import pickle
import json
import glob
from tqdm.auto import trange, tqdm
import openai
from features import merge_entries, prepare_entry
import nltk
from utills import chunker, get_num_chunks
import numpy as np
from nltk.tokenize import sent_tokenize

In [3]:
PREPROCESSED_DATA_PATH = '../temp_data/pan/'

In [4]:
TEMP_DATA_PATH = '/scratch/jnw301/authorship_verification/temp_data/gpt3/'

In [5]:
def get_chunks(entries, sent_size=10):
    text =  ' '.join([e['preprocessed'] for e in entries])
    return [' '.join(c) for c in chunker(sent_tokenize(text), sent_size)]

In [6]:
openai.api_key = "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"

In [8]:
fanfic = 'The city became home since I was eighteen years old when I joined the team. Friends with people that I would never have thought I will become friends with. Especially with Thor and Loki. SInce childhood my knowledge of Norse mythology grew and grew, not knowing why. Now I know why, but still.... Will my life be better in Asgard? Or should I stay in Midgard hoping for the best? I am so confused! "Lady Alexandra?" Turning around, Thor and Loki stand there staring back. "We were speaking with the team and we all agreed on something," Thor speaks up. "What is it?" I asked. "Everyone believes that you life will be better if you come with us to Asgard," Loki explains. I dropped my drink and it shattered at my feet. "What?"'

In [6]:
SYSTEM_PROMPT = (
    "You are an assistant to a fanfiction writer. When the user submits a paragraph of the fanfiction, write the next "
    "thirty paragraphs of the fanfiction in the same writing style as the user."
)

In [10]:
response

<OpenAIObject chat.completion id=chatcmpl-6qsBoAmVBI1AAJYZVTCZJVmeC2FDH at 0x14dd52273770> JSON: {
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "I exclaimed, looking between the two gods in shock. \"You want me to come to Asgard with you?\" Thor gave me a sympathetic smile, placing large hands on my shoulders. \"Lady Alexandra, there are unseen threats on this world, threats that could harm you. If you come with us to Asgard, we can protect you.\" Loki gave me a smile as well, but it seemed like it was more out of amusement than sympathy. I felt my mind reeling at the thought of leaving everything behind for a world full of magic and gods. \"But what about my life here?\" I protested. \"My job, my friends...\" Thor shook his head. \"We can help you create a new life in Asgard. And as for your friends, they will understand that you're needed elsewhere.\" I couldn't deny the logic behind Thor's words. And maybe, just maybe, g

In [7]:
openai.api_key = "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"

def generate(text, fandom):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text}
        ]
    )

    r = response.to_dict()['choices'][0]['message']['content']
    return r

In [12]:
response = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role": "system", "content": "You are an assistant to a fanfiction writer. When the user submits a paragraph of the fanfiction, write the next thirty paragraphs of the fanfiction in the same writing style as the user. "},
        {"role": "user", "content": fanfic}
    ]
)

AttributeError: module 'openai' has no attribute 'ChatCompletion'

In [8]:
def generate_chatgpt_and_human_text_pair(nltk_tokenizer, preprocessed_doc, fandom):
    chunks = get_chunks(preprocessed_doc)
    human_texts = [c for i, c in enumerate(chunks) if i % 2 == 0][:1]
    prompt_texts = [c for i, c in enumerate(chunks) if i % 2 == 1][:1]
    
    
    generated_texts = [generate(p, fandom) for p in prompt_texts]
    generated_text = '\n'.join(generated_texts)
    
    spans = list(nltk_tokenizer.span_tokenize(generated_text))
    groups = chunker(spans, 110)
    generated_texts_preprocessed = [prepare_entry(generated_text[spans[0][0]:spans[-1][1]], mode='accurate', tokenizer='casual') for spans in groups]
    return preprocessed_doc, generated_texts_preprocessed

In [9]:
def merge_and_get_text(entries):
    return ' '.join([e['preprocessed'] for e in entries])

In [10]:
nltk_tokenizer = nltk.tokenize.WhitespaceTokenizer()

In [11]:

path = PREPROCESSED_DATA_PATH + 'preprocessed_test.jsonl'
max_length = 1024
sent_chunk_sz = 25
max_fanfics = 10
prompts = []
i = 0
with open(path, 'r') as f:
    for l in tqdm(f, total=max_fanfics//2):
        d = json.loads(l)
        preprocessed_doc, generated_texts_preprocessed = generate_chatgpt_and_human_text_pair(nltk_tokenizer, d['pair'][0], d['fandoms'][0])
        break
        

AttributeError: module 'openai' has no attribute 'ChatCompletion'

In [11]:
already_generated_ids = []
with open(TEMP_DATA_PATH + 'human_gpt3_preprocessed.jsonl', 'r')  as f:
    for l in f:
        d = json.loads(l)
        already_generated_ids.append(d['id'])

In [12]:
len(already_generated_ids)

84

In [55]:

max_fanfics = 20

In [13]:
with open(TEMP_DATA_PATH + 'human_gpt3_preprocessed.jsonl', 'a') as f_out, open(PREPROCESSED_DATA_PATH + 'preprocessed_test.jsonl', 'r') as f:
    for l in tqdm(f):
        d = json.loads(l)
        if d['id'] in already_generated_ids:
            continue
        d1_human, d1_ai = generate_gpt3_and_human_text_pair(nltk_tokenizer, d['pair'][0], d['fandoms'][0])
        d2_human, d2_ai = generate_gpt3_and_human_text_pair(nltk_tokenizer, d['pair'][1], d['fandoms'][0])

        preprocessed = {
            'id': d['id'],
            'fandoms': d['fandoms'],
            'pair': [
                {'human': d1_human, 'ai': d1_ai},
                {'human': d2_human, 'ai': d2_ai}
            ]
        }
        json.dump(preprocessed, f_out)
        f_out.write('\n')
        f_out.flush()

0it [00:00, ?it/s]

674 1400
793 1820
570 1437
610 1538
925 1750
671 1503
704 1563
412 1396
746 1355
994 1430
599 1824
781 1611
752 1906
719 1902
548 1820
855 1235
1055 1696
673 1715
748 1501
556 1457
1092 1496
846 1795
709 1559
932 1005
808 1717
659 1838
574 1074
432 1622
674 1660
793 1820
570 1768
610 1458
925 1254
671 1571
704 1585
412 1582
746 1875
994 1430
599 1824
781 1653
752 1883
719 1540
548 1580
747 1563
1050 1806
724 1743
795 2223
897 2019
899 2168
753 2033
743 1690
658 1533
830 1203
794 1607
741 1612
502 1362
902 1460
1039 1884
1154 1644
952 1854
888 941
1348 1233
896 1130
645 1637
1105 1519
1048 1313
783 2644
744 1675
939 2245
358 1686
883 2226
619 2000
807 1838
1014 2120
891 1182
780 2323
943 1024
538 1925
1248 1465
890 1372
439 1921
902 1816
1039 1738
1154 1644
952 1747
888 941
1348 1526
896 1130
645 1637
1105 1519
1048 1554
783 1619
747 1232
1050 1749
724 2076
795 2255
897 1677
899 1864
753 2264
743 1877
658 1412
830 1435
794 2095
741 1555
502 1430
855 1443
1055 1879
673 2361
748 1454
556 

RateLimitError: You exceeded your current quota, please check your plan and billing details.

In [38]:
chunks = get_chunks(d['pair'][0])
human_texts = [c for i, c in enumerate(chunks) if i % 2 == 0][:4]

In [43]:
preprocessed_doc, generated_texts_preprocessed = generate_gpt3_and_human_text_pair(nltk_tokenizer, d['pair'][0], d['fandoms'][0])




Complete the next ten paragraphs of this fanfiction about Avengers:
"Jane what is wrong with you?" "Nothing"s wrong with me!" It becomes into a shouting fight. Little did we know, the whole team is watching from the tower. *The Tower* *No One"s POV* Tony let out a whistle before speaking, "they never fight like this." "What are we going to do?" Natasha asked. "Her behavior is worser than I thought," Father George sighs, pinching the bridge of his nose, "if she continues to be in denial, a death will occur." "How can you be sure?" Pepper asked, worried for her friend. "I have been on Alexandra"s side for many years trying to keep positivity around her because she has a "curse" on her." "What kind of curse?" Bruce asked, catching his attention. "She lost her biological parents at the age of three, making her an orphan. Jane"s parents adopted her and made her life like hell until she was thirteen years old.


Response:


At that age, she was able to escape and find a place to stay. She

In [54]:
len(merge_entries(preprocessed_doc)['tokens'])

4907

In [45]:
len(merge_entries(generated_texts_preprocessed)['tokens'])

3530

GPT3
---

In [37]:
print(merge_entries(generated_texts_preprocessed)['preprocessed'])

Thor nodded in agreement, "It is strange. I have never seen them fight like this before." Steve stepped forward, "We should go down there and see what's going on." The team agreed and they all headed down to the lab.

When they arrived, Jane and I were still arguing. Tony stepped in between us and said, "What's going on here?" We both looked at him with surprise. Jane was the first to speak, "It's nothing Tony, just a misunderstanding." I nodded in agreement but Tony wasn't convinced. He looked at us both with a stern expression before saying, "I think it's time for you two to talk this out."

We
both reluctantly agreed and sat down on the couch. Jane started off by apologizing for her outburst and explained why she had reacted that way. She told me that she was worried about Father George because he had been acting strange lately. She thought he might be getting into some kind of trouble and didn't want me to get involved. 

I understood her concern but told her that Father George was

Human
---

In [72]:
print(merge_entries(preprocessed_doc)['preprocessed'])

"Because it"s my dream home," she smiled, feeling proud of herself. "No it"s not," I said confused. "Yes it is!" "I know your dream home and that"s not your dream home. What ever happened to our plans of living in a forest so we can get away from everything?" "Hey a girl can change her mind." "Jane," I sighed, pulling out the envelop with the sketches, "I love you and I don"t want anything to happen to you." I give her the sketches. "These are sketches of the beings that are both haunting your home and influencing you. Father George
is willing to help you." As soon as I said the name of my "guardian", she gave me a disgusting look. "There"s no need for him," she speaks coldly. This took me by surprise. Jane loves Father George like a fatherly figure like I do. So having her speak coldly of him was unnerving. "Jane what is wrong with you?" "Nothing"s wrong with me!" It becomes into a shouting fight. Little did we know, the whole team is watching from the tower. *The Tower* *No One"s POV

In [73]:
predict_pan(
    [preprocessed_doc], [generated_texts_preprocessed],
    clf_pan, transformer_pan, scaler_pan, secondary_scaler_pan
)

array([0.30874729])

Second fanficion
----

In [59]:
preprocessed_doc, generated_texts_preprocessed = generate_gpt3_and_human_text_pair(nltk_tokenizer, d['pair'][1], d['fandoms'][1])




Complete the next ten paragraphs of this fanfiction about Harry Potter:
"Yes I do, but I know nothing of the second part," Lady Luna admits, blushing in embarrassment. "Have you been reading your Potions book?" I asked, a little curious. "No," she bows her head in defeat. "Busy with magical creature watching?" I smirked, remembering a few times that I saw her. "Maybe." I chuckled a little. "Well I know that you love magical creatures just as much as I do, but you need to focus on your education so you can become a Magizoologist." "I know, but I can"t help it," she says with a sigh. "Are you planning on going into Care of Magical Creatures next year?" "Yes I am!" the blond haired girl grinned. "That"s brilliant now what is the second part of the Swelling Solution?" I smirked more with a chuckle. "Now I see why your soulmate is in Slytherin," she giggles, knowing the situation that I have. "Yea," I giggled a little more. "Now once the sixty minutes are up, you must add one bat spleen 

GPT3
---

In [60]:
print(merge_entries(generated_texts_preprocessed)['preprocessed'])

"Then add two tablespoons of powdered root of asphodel and stir seven times clockwise," I continued. "After that, add three drops of leech juice and stir nine times anti-clockwise." Lady Luna nodded her head in understanding, writing down the instructions. "Finally, add one teaspoon of powdered horn of a bicorn and stir eleven times clockwise," I finished. Lady Luna looked up at me with a smile, thanking me for my help. "No problem," I smiled back. "Now you just have to wait for the potion to swell and then you can bottle it up." She nodded her head in agreement before turning back to her cauldron. 

I watched as she
carefully followed the instructions that I had given her, stirring the potion slowly and precisely. After a few minutes, the potion began to bubble and swell until it was twice its original size. Lady Luna smiled in satisfaction before carefully bottling it up and setting it aside for later use. 

"Thank you so much for your help," she said gratefully as she wiped her hand

Human
---

In [61]:
print(merge_entries(preprocessed_doc)['preprocessed'])

"Okay there are three main ingredients, what are they?" I started lecturing her. "The three main ingredients are bat spleens, dried nettles, and.....umm..." she"s having problems with the last one. "Puffer fish eyes," I smiled. "Puffer fish eyes?" she asked confused. "Yep, now there"s a two part step in the brewing process. What do you do for the first one?" I asked. "Add two scoops of dried nettle to the mortar then add three puffer fish eyes to the mortar," she begins, writing it down. "That"s good, now what else?" "Crush the mixture into a medium fine powder." "Good, after
adding two measures of the crushed mixture to your cauldron, what do you do next?""Heat the cauldron over a medium temperature for twenty seconds and then wave your wand.""Now what do you do last in the first part?" "Uhh....ummm..." I smirked a little. "Leave it brew and return in sixty minutes or depending on the type of cauldron that you have," I add in. "Only sixty minutes?" "Yes, no more or less. Now do you ha

In [66]:
predict_pan(
    [preprocessed_doc], [generated_texts_preprocessed],
    clf_pan, transformer_pan, scaler_pan, secondary_scaler_pan
)

array([0.3381095])

In [76]:
predict_pan(
    [d['pair'][0]], [d['pair'][1]],
    clf_pan, transformer_pan, scaler_pan, secondary_scaler_pan
)

array([0.98779936])